defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: best_regresion_model
    storage: null
    n_trials: 500
    n_jobs: 1

    search_space:
      x:
        type: float
        low: -5.5
        high: 5.5
        step: 0.5
      y:
        type: categorical
        choices: [-5, 0, 5]
      z:
        type: int
        low: 1
        high: 32
        log: true

      optimizer:
        type: categorical
        choises: [Adam, RMSprop, SGD]
      lr:
        type: foat
        low: 0.001
        high: 0.01
        step: 0.0001


x: 1
y: 1
z: 1